[fleet]
# Fleet server URL (required)
# Replace with your actual Fleet instance URL
server_url = "https://fleet.example.com"

# Fleet API token (required)
# Get this from Fleet UI: My account > Get API token
# For SSO/MFA users, this is the only way to get an API token
api_token = "your-api-token-here"

# Verify SSL certificates (default: true)
# Set to false only for development/testing with self-signed certificates
verify_ssl = true

# Request timeout in seconds (default: 30)
# Increase for slow networks or large queries
timeout = 30

# Maximum number of retries for failed requests (default: 3)
# Helps with transient network issues
max_retries = 3

# Enable read-only mode (default: false)
# When true, only read operations are available (no create/update/delete)
readonly = false
