name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install uv
        run: pip install uv
        
      - name: Install dependencies
        run: uv sync --dev
        
      - name: Run unit tests
        run: uv run pytest -m unit --cov=fleet_mcp --cov-report=xml
        
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: matrix.python-version == '3.10'

  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Install uv
        run: pip install uv
        
      - name: Install dependencies
        run: uv sync --dev
        
      - name: Check formatting
        run: uv run black --check src tests
        
      - name: Check imports
        run: uv run isort --check-only src tests
        
      - name: Lint
        run: uv run ruff check src tests

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Install uv
        run: pip install uv
        
      - name: Install dependencies
        run: uv sync --dev
        
      - name: Type check
        run: uv run mypy src